#!/bin/bash

# set environment variables required to run custom Arbor installation
source set_arbor_env

# run the simulation with noise
python3 ./arbor2N1S.py -learn=predef -runtime=200 -data_saving=0

# run the simulation without noise
python3 ./arbor2N1S.py -learn=predef_no_pl_noise -runtime=200 -data_saving=0
